### ISSUE TITLE
consider using hupper for reloading

### ISSUE THREAD

**Issue by mmerickel** [TurboGears/gearbox#14]
Hey folks, I've done a lot of work in Pyramid's pserve (which of course is derived from PasteScript -
 the same code as gearbox's serve command) to make the reloader smarter. One major feature is that it does not crash when your code fails to start, so you do not need to continually restart it. The library that does this was pulled out into a framework-agnostic entity called hupper.

http://docs.pylonsproject.org/projects/hupper/en/latest/

Anyway, I just wanted to bring it to your attention incase you are interested in using it for an improved `--reload` experience.

**Comment by amol-** [comment]
@mmerickel I had a quick look into this and there is one thing that concerns me.

gearbox serve has `--monitor-restart` option which will restart the server if it crashes and doesn't seem it would easily integrate with hupper without having 2 huppers running.

The `--monitor-restart` feature pretty much spawns a subprocess and checks if it's still running, if it dies it respawns it.

Once hupper gets integrated hupper can be in two different situations:

1. It can be the parent of the `--monitor-restart` process
2. It can be the child of the `--monitor-restart` process

Seems both cases would have some problems that are not easy to work around:

1. As hupper is the parent of the `--monitor-restart` process it would detect code changes in gearbox but not in the web application as it monitors `sys.modules` and the application modules are not loaded in the `--monitor-restart` process as it only acts as an angel the process actually serving the app is an inner one.
2. As hupper is the child of `--monitor-restart` process it would properly detect code changes, but it looks like in this case the `--monitor-restart` process would be unable to detect a server crash as it would be monitoring hupper and looks like hupper doesn't quit if the server crashes. See:

```
import time
import hupper


def main():
    if not hupper.is_active():
        hupper.start_reloader('restarttest.main')
        return

    for i in range(1, 4):
       print 'Counting %s...' % i
       time.sleep(1.0)

    print 'Crashing... now hupper will hang forever'
    raise RuntimeError('e')


if __name__ == '__main__':
    main()
```

I would like to go for solution *2* as it seems a more natural structure, but it's odd that hupper hangs forever instead of quitting if the process it's monitoring crashes.

**Comment by mmerickel** [comment]
A couple points:

1) We actually removed `--monitor-restart` and all daemonization options / process management from pserve because we felt it was bad practice to try to act as a supervisor when there are plenty of other purpose-built options.

2) `--monitor-restart` was always incompatible with `--reload` in pserve - they stepped on eachother's toes similar to what you're describing.

3) It's a major feature of `hupper` to hang instead of quitting. It does not crash when your program crashes... it waits for you to save changes and starts it again. Without a feature like this (versus something like `--monitor-restart`) your program would end up just restarting in an infinite loop until you fixed your problem.

My suggestion would be to make `--monitor-restart` mutually exclusive with `--reload` and then you have no problems in this area. The former is for more production scenarios and the latter is for development.

**Comment by amol-** [comment]
Yep, my fallback was to make them mutually exclusive, but I wanted to preserve same exact behaviour because there are people actually serving through gearbox on production and I don't want to break their environments.

I hoped there was a way to start hupper in a "don't hang" way when `--monitor-restart` was used so that even though it would face the infinite restart loop you described it would have preserved the existing behaviour.

I'll just go for making the mutually exclusive.

**Comment by amol-** [comment]
https://github.com/TurboGears/gearbox/commit/5d81078af3ac194345cbf183f5304d2fc3390848

**Comment by mmerickel** [comment]
Awesome! I hope that you find hupper to be an improvement for development. :-)
