### ISSUE TITLE
ssl server

### ISSUE THREAD

**Issue by alexbodn** [TurboGears/gearbox#8]
hello friends,

i'm happily using turbogears for ages, but realized with horror that all my development work, 
including manager logins, went in the open http.

i took tg 2.3.7 for a new project, but this time i wish to begin development in a secure environment, 
so i applied the included patch to allow working with ssl.

i'd thank you in advance if you could share my patch with the public.
alex
[gearbox-ssl.zip](https://github.com/TurboGears/gearbox/files/101653/gearbox-ssl.zip)

**Comment by moschlar** [comment]
Well, normally you run the development server on your own local machine (that's why it listens on 127.0.0.1 by default) so there is no need for that.
Of course there might be scenarios in which it could be required to develop on a remote machine, so it might not be the worst idea to have optional SSL support, though it might encourage users to use it for the wrong situation then:
For any kind of production-y environment, you should use a *real* wsgi server anyways, if only for performance reasons and normally you have a proxing web server that does the SSL termination in front of that as well.

Also, in the comment in your file you generate a 1024 bit RSA key, which is too small nowadays. Use at least 2048 or even better 4096 bit keys there.
And finally, why did you not submit this patch as a GitHub pull request? That would just make it easier to integrate it with proper attribution.

**Comment by amol-** [comment]
Uhm, this is an interesting issue.

While @moschlar is right and usually https support is not a concern during development, it might be helpful when you have to work or test parts of the website that has to forward the user to HTTPS and back. Currently working on those it's not easy unless you put an HTTPS server in front of gearbox on your machine and SSL support would probably help for that use case if Gearbox wsgiref server is able to respond on both HTTP and HTTPS.

For the "security of development environment" it should usually run on your loopback address and you usually have different users and passwords between development and production so it shouldn't be a major concern. But making easier to work on websites that have to send the user back and forth from HTTPS might be an interesting improvement.

**Comment by alexbodn** [comment]
hello friends, 

thank you for considering my issue.

indeed my case is on site debugging a running site, it's very database and user session, so that the authentication would coincide.

about switching back and forth http and https addresses, i am transforming 
the scheme part in a function, say http[s]?_url(url). 
that function would select the single applying scheme when the host_name contains the port.

however you may say my scenario isn't optimal, but i'm accessing my host by ssh, and don't have a gui there for the browser at all.
so please, mind to apply my patch, and let the system defend users like me of their own clumsiness.

last but not least, i wish to credit dropbox, for the code is from an older version of their rest client.
this is the still active url: https://github.com/sourcegraph/dropbox/raw/master/tests/test_rest.py

many thanks in advance,
alex
